// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QHCuzrAYOASuH1R6LzWgCVkbLuWJRnE',
    appId: '1:275613981678:web:a3b76d8052d7913bf90cff',
    messagingSenderId: '275613981678',
    projectId: 'recipeapp-edda9',
    authDomain: 'recipeapp-edda9.firebaseapp.com',
    storageBucket: 'recipeapp-edda9.firebasestorage.app',
    measurementId: 'G-ZJXQB41WYZ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0QHCuzrAYOASuH1R6LzWgCVkbLuWJRnE',
    appId: '1:275613981678:web:e5e4d02525768da0f90cff',
    messagingSenderId: '275613981678',
    projectId: 'recipeapp-edda9',
    authDomain: 'recipeapp-edda9.firebaseapp.com',
    storageBucket: 'recipeapp-edda9.firebasestorage.app',
    measurementId: 'G-Z251WMJZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0cKG-zk2Ti_gbOqFCnmICtizIsdwPH3A',
    appId: '1:275613981678:android:b8919676e6628c90f90cff',
    messagingSenderId: '275613981678',
    projectId: 'recipeapp-edda9',
    storageBucket: 'recipeapp-edda9.firebasestorage.app',
  );

}