name: recipe_app
description: "Recipe App - Jordan & Adam"

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  fake_cloud_firestore: ^3.1.0
  google_sign_in: ^6.2.2
  mockito: ^5.4.0
  provider: ^6.1.2
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner:
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
